{
 "title": "Cyclic Retentive Backup",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vplc_instance",
    "label": "S7-1500V Instance",
    "query": {
     "query": "label_values(crb_successful_cycle_count, vplc_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cycle Extension Durations",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 17, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(cycle_extension_bucket{vplc_instance=\"$vplc_instance\"}[$__rate_interval]), 1)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Successfully Written Cycles",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(crb_successful_cycle_count{vplc_instance=\"$vplc_instance\"}[$__range])"
    },
    {
     "expr": "increase(crb_total_cycle_count{vplc_instance=\"$vplc_instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "Min Extension Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crb_min_cycle_extension_duration{vplc_instance=\"$vplc_instance\"}"
    }
   ]
  },
  {
   "title": "Min Write Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crb_min_write_duration{vplc_instance=\"$vplc_instance\"}"
    }
   ]
  },
  {
   "title": "Max Extension Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crb_max_cycle_extension_duration{vplc_instance=\"$vplc_instance\"}"
    }
   ]
  },
  {
   "title": "Max Write Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crb_max_write_duration{vplc_instance=\"$vplc_instance\"}"
    }
   ]
  },
  {
   "title": "Data Write Durations",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 17, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(write_duration_bucket{vplc_instance=\"$vplc_instance\"}[$__rate_interval]), 1)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Average Extension Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(crb_sum_cycle_extension_duration{vplc_instance=\"$vplc_instance\"}[$__rate_interval])"
    },
    {
     "expr": "increase(crb_successful_cycle_count{vplc_instance=\"$vplc_instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Average Write Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(crb_sum_write_duration{vplc_instance=\"$vplc_instance\"}[$__rate_interval])"
    },
    {
     "expr": "increase(crb_successful_cycle_count{vplc_instance=\"$vplc_instance\"}[$__rate_interval])"
    }
   ]
  }
 ]
}